.\" (c) 1997-2001 **Quake II** - Id Software, Inc.
.\" (c) 2002 Vipersoft
.\" (c) 2003-2011 **Q2PRO** - Andrey Nazarov [skuller]
.\" (c) 2018 Carlos Donizete Froes [a.k.a coringao]
.\"
.\" This document is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This package is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this package; if not, see <http://www.gnu.org/licenses/>.
.br
.TH dday-normandy "6" "September 2018" "D-DAY: Normandy"
.SH NAME
dday-normandy \- The first person game of World War II where you can play
in online multiplayer or singleplayer.
.br
.PP
.SH CONTROLS
.br
.B Keyboard - Basic
.br
================
.PP
.B	KEY						ACTION
.br
---						------
.PP
ESC (Escape):				Main menu
.br
[, ], PAGE DOWN, PAGE UP:	Up/Down in game menu
.br
A, S, D, W or ARROWS:		Character Movements
.br
Q:						Take items
.br
SPACE:					Jump
.br
C or CTRL:				Down-crouch
.br
R:						Reload
.br
.PP
.B Mouse Controls
.br
==============
.PP
.B	CLICK					ACTION
.br
-----					------
.PP
LEFT CLICK:				Shoot
.br
RIGHT CLICK:				Using the gun in position to aim
.br
MIDDLE CLICK:				Reload
.br
.PP
.SH AUTHORS
**Quake II** - Id Software, Inc.
.br
**Q2PRO** - Andrey Nazarov [skuller]
.br
D-DAY: Normandy created by Vipersoft and enhanced by other volunteers.
.br
This manual page was written by Carlos Donizete Froes [a.k.a coringao],
for the Debian project (but may be used by others).
